apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: spring-boot-demo
spec:
  selector:
    app: elasticsearch-service
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      nodePort: 30200
  type: NodePort