apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-service
  namespace: spring-boot-demo
spec:
  replicas: 1
  selector:
    app: elasticsearch-service
  template:
    metadata:
      labels:
        app: elasticsearch-service
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.12.2
          ports:
            - containerPort: 9200
              name: db
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          env:
            - name: DISCOVERY_TYPE
              value: single-node
            - name: XPACK_SECURITY_ENABLED
              value: false
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 500Mi