apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: spring-boot-demo
spec:
  selector:
    app: elasticsearch-service
  ports:
    - name: db
      port: 9200
      targetPort: 9200
      protocol: TCP
      nodePort: 30200
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
      nodePort: 30300
  type: NodePort