apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: spring-boot-demo
spec:
  selector:
    app: mysql-service
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: 30006
  type: NodePort