apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mysql-service
  namespace: spring-boot-demo
  labels:
    kubernetes.io/service-name: mysql-service
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 3306
endpoints:
  - addresses:
      - "192.168.65.9"
