apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: spring-boot-demo
spec:
  selector:
    app: redis-service
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 30379
  type: NodePort