apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-service
  namespace: spring-boot-demo
spec:
  replicas: 1
  selector:
    app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          ports:
            - containerPort: 6379