server:
  servlet:
    session:
      timeout: 10
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://192.168.100.165:30006/spring_boot_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: steve.springboot.wechat.demo.domain