server:
  servlet:
    session:
      timeout: 10
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_test?serverTimezone=UTC
    username: root
    password: password
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
