apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-service
  namespace: spring-boot-demo
spec:
  replicas: 1
  selector:
    app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
        - name: mysql
          image: mysql:8.3.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root