apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-service
  namespace: spring-boot-demo
spec:
  replicas: 1
  selector:
    app: mongodb-service
  template:
    metadata:
      labels:
        app: mongodb-service
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0.5
          ports:
            - containerPort: 27017