apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: spring-boot-demo
spec:
  selector:
    app: mongodb-service
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 37017
  type: NodePort