apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-service
  namespace: spring-boot-demo
spec:
  replicas: 1
  selector:
    app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          ports:
            - containerPort: 9092
          env:
            - name: listeners
              value: "PLAINTEXT://192.168.1.4:30092"
            - name: advertised.listeners
              value: "PLAINTEXT://192.168.1.4:30092"
            - name: zookeeper.connect
              value: "192.168.1.4:30092"