apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: spring-boot-demo
spec:
  selector:
    app: kafka-service
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      nodePort: 30092
  type: NodePort