spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring
    elasticsearch:
      cluster-name: es
      cluster-nodes: localhost:9200
  elasticsearch:
    rest:
      uris: ["http://localhost:9200"]
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8444
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
logging:
  level:
    root: error
    org:
      springframework:
        web: error