spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.4:30017/spring
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.4:30200
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: ["http://192.168.1.4:30200"]
  kafka:
    bootstrap-servers: 192.168.1.4:30092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
server:
  port: 8444
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
logging:
  level:
    root: info
    org:
      springframework:
        web: error
