spring:
  datasource:
    dbcp2:
      max-idle: 10
      max-wait-millis: 30
      min-idle: 5
      initial-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
server:
  servlet:
    session:
      timeout: 10
  port: 8080
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: steve.springboot.wechat.demo.domain